---
title: "cuffdiff2"
author: "zhu"
date: "2017/8/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(pheatmap)
```

```{r}
ddir = file.path("~/workspace/6.muscle_ageing/5.RNA_analysis/3.cuffdiff")
gene_exp.diff <- read.table("~/workspace/6.muscle_ageing/5.RNA_analysis/3.cuffdiff/gene_exp.diff",header = T,row.names = 1)
genes.read_group_tracking <- read.table("~/workspace/6.muscle_ageing/5.RNA_analysis/3.cuffdiff/genes.read_group_tracking",header = T)
fpkmMatrix.tab <- read.table("~/workspace/6.muscle_ageing/5.RNA_analysis/3.cuffdiff/fpkmMatrix.tab",header = T,row.names = 1)

#fpkmMatrix.tab$status <- gene_exp.diff[rownames(fpkmMatrix.tab),"status"]
fpkmMatrix.ok <- fpkmMatrix.tab[which(gene_exp.diff$status == "OK"),]



```

```{r pca plot }
pca.ok <- prcomp(t(fpkmMatrix.ok),scale. = T)
percentVar <- summary(pca.ok)$importance[2,1:2]
pc12 <- data.frame(pca.ok$x[,1:2])
pc12$condition <- factor(unlist(lapply(strsplit(rownames(pc12),"_"),function(x) x[1])))
pc12$replicate <- factor(unlist(lapply(strsplit(rownames(pc12),"_"),function(x) x[2])))

ggplot(data=pc12, aes(PC1, PC2)) + 
  geom_point( aes(color = condition, shape = replicate) , size =4 ) +#,shape =paper 
  #geom_text(label=rownames(data_pca_x))
  #scale_color_manual(values = c("green","red")) + 
  #    scale_shape_manual(values=c(16,1,17,2)) +
  # scale_shape_manual(values=c(16,17)) + 
  #    scale_size_manual(values = c(2,4)) + 
  xlab(paste0("PC1: ",percentVar[1]*100,"% variance")) + 
  ylab(paste0("PC2: ",percentVar[2]*100,"% variance")) +
  geom_hline(yintercept = 0 , linetype="dashed")+
  geom_vline(xintercept = 0 , linetype="dashed")+
  scale_color_manual(values = c("red","green"))
```



```{r pheatmap}
select <- grep("Hoxa",rownames(fpkmMatrix.ok))
select <- rownames(gene_exp.diff[which(gene_exp.diff$significant == "yes" & abs(gene_exp.diff$log2.fold_change.) > 0.585),])
pheatmap(log2(fpkmMatrix.ok[select,]), cluster_rows=T, show_rownames=T,cluster_cols=T)

```

```{r volcano plot}
res_frame <- gene_exp.diff[gene_exp.diff$status == "OK",c("log2.fold_change.","p_value")]
colnames(res_frame) <- c("log2FoldChange","pvalue")
with(res_frame, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot"))
res_frame$change <- as.factor(ifelse(res_frame$pvalue < 0.05 & abs(res_frame$log2FoldChange) > log2(1.5),
                               ifelse(res_frame$log2FoldChange > 0, "UP", "DOWN"), "NOT"))

g = ggplot(data=res_frame, aes(x=log2FoldChange, y=-log10(pvalue), color=change)) +
  geom_point(alpha=0.5, size=1,na.rm = T) +
  theme_set(theme_set(theme_bw(base_size=20)))+
  xlab("log2 fold change") + ylab("-log10 pvalue") +
  #ggtitle( this_tile  ) + theme(plot.title = element_text(size=15,hjust = 0.5))+
  scale_colour_manual(values = c('darkgreen','grey','red'))  ## corresponding to the levels(res$change)

spe_genes <- c("Hoxa9","Hoxa10","Hoxa1","Hoxc1")
spe_frame <- res_frame[spe_genes,]
spe_frame$name <- as.factor(rownames(spe_frame))

g2 <- g + 
  geom_point(aes(x=log2FoldChange, y=-log10(pvalue)), data = spe_frame, color="yellow")+
  geom_text(aes(x=log2FoldChange, y=-log10(pvalue),label=name,vjust=-1,hjust=-0.1), data = spe_frame,color="black")

print(g2)
ggsave("muscle_ageing_volcano_plot_cuffdiff2.png",g2)

```
